#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/* automatically generated by rust-bindgen 0.66.1 */

pub const DES_BLOCK_SIZE: u32 = 8;
type BYTE = ::core::ffi::c_uchar;
type WORD = ::core::ffi::c_uint;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum DES_MODE {
    DES_ENCRYPT = 0,
    DES_DECRYPT = 1,
}
extern "C" {
    #[doc = " FUNCTION DECLARATIONS"]
    pub fn des_key_setup(key: *const BYTE, schedule: *mut [BYTE; 6usize], mode: DES_MODE);
}
extern "C" {
    pub fn des_crypt(in_: *const BYTE, out: *mut BYTE, key: *const [BYTE; 6usize]);
}
extern "C" {
    pub fn three_des_key_setup(
        key: *const BYTE,
        schedule: *mut [[BYTE; 6usize]; 16usize],
        mode: DES_MODE,
    );
}
extern "C" {
    pub fn three_des_crypt(in_: *const BYTE, out: *mut BYTE, key: *mut [[BYTE; 6usize]; 16usize]);
}
