[package]
name = "amll-player-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
concat-string = "^1.0"
cpal = "^0.15"
futures = "0.3"
md5 = "^0.7"
rb = "^0.4"
ringbuf = "^0.3"
rubato = "^0.15"
arrayvec = "^0.7"
segmap = "0.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
spectrum-analyzer = "1.5"
symphonia = { version = "^0.5", features = ["all", "opt-simd"] }
tempfile = "^3.8"
tokio = { version = "1.35.0", features = ["time", "macros", "sync", "rt", "rt-multi-thread"] }
tracing = "0.1"

[dependencies.ffmpeg-next]
optional = true
version = "7.1.0"
default-features = false
features = ["codec", "format"]

[target.'cfg(target_os = "windows")'.dependencies]
tempfile = "^3"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58"
features = [
    "Media",
    "Media_Playback",
    "Storage_Streams",
    "Win32_System_WinRT",
]

[target.'cfg(target_os = "linux")'.dependencies]
mpris-server = "0.8"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.5"
block2 = "0.5"
once_cell = "^1.18"
[target.'cfg(target_os = "macos")'.dependencies.objc2-media-player]
version = "0.2"
features = [
    "MPRemoteCommand",
    "MPRemoteCommandEvent",
    "MPRemoteCommandCenter",
    "MPNowPlayingInfoCenter",
    "MPMediaItem",
    "block2",
    "objc2-app-kit",
]
[target.'cfg(target_os = "macos")'.dependencies.objc2-app-kit]
version = "0.2"
features = [
    "NSImage",
]
[target.'cfg(target_os = "macos")'.dependencies.objc2-foundation]
version = "0.2"
features = ["all"]

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
